local black = "#393842"
local gray = "#9fa0a6"
local purple = "#a625a4"
local blue = "#4078f1"
local cyan = "#0083bb"
local green = "#50a04f"
local yellow = "#b66a00"
local orange = "#e35549"
local red = "#c91142"

local h = {
  ["@attribute"] = { fg = purple }, -- maybe
  ["@attribute.builtin"] = { fg = purple }, -- maybe
  ["@boolean"] = { fg = yellow },
  ["@character"] = { fg = green },
  ["@character.special"] = { fg = black },
  ["@comment"] = { fg = gray },
  ["@comment.documentation"] = { fg = gray },
  ["@comment.error"] = { fg = gray },
  ["@comment.note"] = { fg = gray },
  ["@comment.todo"] = { fg = gray },
  ["@comment.warning"] = { fg = gray },
  ["@constant"] = { fg = yellow },
  ["@constant.builtin"] = { fg = orange },
  ["@constant.macro"] = { fg = red },
  ["@constructor"] = { fg = black },
  ["@diff.delta"] = { fg = cyan },
  ["@diff.minus"] = { fg = red },
  ["@diff.plus"] = { fg = green },
  ["@function"] = { fg = blue },
  ["@function.builtin"] = { fg = cyan },
  ["@function.call"] = { fg = black },
  ["@function.macro"] = { fg = red },
  ["@function.method"] = { fg = blue },
  ["@function.method.call"] = { fg = black },
  ["@keyword"] = { fg = purple },
  ["@keyword.conditional"] = { fg = purple },
  ["@keyword.conditional.ternary"] = { fg = black },
  ["@keyword.coroutine"] = { fg = purple },
  ["@keyword.debug"] = { fg = purple },
  ["@keyword.directive"] = { fg = purple },
  ["@keyword.directive.define"] = { fg = purple },
  ["@keyword.exception"] = { fg = purple },
  ["@keyword.function"] = { fg = purple },
  ["@keyword.import"] = { fg = purple },
  ["@keyword.modifier"] = { fg = purple },
  ["@keyword.operator"] = { fg = purple },
  ["@keyword.repeat"] = { fg = purple },
  ["@keyword.return"] = { fg = purple },
  ["@keyword.type"] = { fg = purple },
  ["@label"] = { fg = black, bold = true },
  ["@markup.heading"] = { fg = black, bold = true },
  ["@markup.heading.1"] = { fg = black, bold = true },
  ["@markup.heading.2"] = { fg = black, bold = true },
  ["@markup.heading.3"] = { fg = black, bold = true },
  ["@markup.heading.4"] = { fg = black, bold = true },
  ["@markup.heading.5"] = { fg = black, bold = true },
  ["@markup.heading.6"] = { fg = black, bold = true },
  ["@markup.italic"] = { italic = true },
  ["@markup.link"] = { fg = green },
  ["@markup.link.label"] = { fg = black },
  ["@markup.link.url"] = { underline = true },
  ["@markup.list"] = { fg = black },
  ["@markup.list.checked"] = { fg = green },
  ["@markup.list.unchecked"] = { fg = gray },
  ["@markup.math"] = { fg = blue, bold = true },
  ["@markup.quote"] = { fg = green },
  ["@markup.raw"] = { fg = black },
  ["@markup.raw.block"] = { fg = black },
  ["@markup.strikethrough"] = { strikethrough = true },
  ["@markup.strong"] = { bold = true },
  ["@markup.underline"] = { underline = true },
  ["@module"] = { fg = black },
  ["@module.builtin"] = { fg = cyan },
  ["@number"] = { fg = yellow },
  ["@number.float"] = { fg = yellow },
  ["@operator"] = { fg = blue },
  ["@property"] = { fg = black },
  ["@punctuation.bracket"] = { fg = black },
  ["@punctuation.delimiter"] = { fg = black },
  ["@punctuation.special"] = { fg = yellow },
  ["@string"] = { fg = green },
  ["@string.documentation"] = { fg = green },
  ["@string.escape"] = { fg = red },
  ["@string.regexp"] = { fg = green },
  ["@string.special"] = { fg = green },
  ["@string.special.path"] = { fg = green },
  ["@string.special.symbol"] = { fg = green },
  ["@string.special.url"] = { fg = cyan },
  ["@tag"] = { fg = blue },
  ["@tag.attribute"] = { fg = yellow },
  ["@tag.builtin"] = { fg = blue },
  ["@tag.delimiter"] = { fg = black },
  ["@type"] = { fg = yellow },
  ["@type.builtin"] = { fg = yellow },
  ["@type.definition"] = { fg = yellow },
  ["@variable"] = { fg = black },
  ["@variable.builtin"] = { fg = cyan },
  ["@variable.member"] = { fg = black },
  ["@variable.parameter"] = { fg = black },
  ["@variable.parameter.builtin"] = { fg = cyan },
}

return h
